// bridge.cpp - include per compatibilità Arduino IDE
#include "lib/core/Core.cpp"
#include "lib/core/EventBus.cpp"
#include "lib/hardware/DisplayManager.cpp"
#include "lib/hardware/EncoderManager.cpp"
#include "lib/hardware/LEDManager.cpp"
#include "lib/network/WebServerManager.cpp"
#include "lib/network/WiFiManager.cpp"
#include "lib/utils/NTPManager.cpp"
#include "lib/utils/QRCodeManager.cpp"
#include "lib/prefs/PreferencesManager.cpp"
#include "lib/forex/ForexApp.cpp"
#include "lib/forex/ui/ForexDisplayManager.cpp"
#include "lib/forex/services/ForexDataService.cpp"
#include "lib/forex/services/ForexPreferences.cpp"
#include "lib/forex/network/ForexConfigServer.cpp"